it seems to me, same errors keep occuring.
studio-204170810:~/studio{master}$ firebase deploy --only functions:createBotUser

=== Deploying to 'anonycollab'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> lint
> eslint --ext .js,.ts .

/home/user/studio/functions/src/index.ts
   5:9   error  There should be no space after '{'                   object-curly-spacing
   5:31  error  There should be no space before '}'                  object-curly-spacing
   8:1   error  This line has a length of 90. Maximum allowed is 80  max-len
  19:31  error  There should be no space after '{'                   object-curly-spacing
  19:52  error  There should be no space before '}'                  object-curly-spacing
  51:35  error  Missing trailing comma                               comma-dangle

✖ 6 problems (6 errors, 0 warnings)
  5 errors and 0 warnings potentially fixable with the `--fix` option.

Error: functions predeploy error: Command terminated with non-zero exit code 1