fix this and future potential errors: /home/user/studio/functions/src/index.ts     5:9  warning  'generateAnonymousName' is defined but never used    @typescript-eslint/no-unused-vars   127:1  error    This line has a length of 85. Maximum allowed is 80  max-len   131:1  error    This line has a length of 87. Maximum allowed is 80  max-len   151:1  error    This line has a length of 85. Maximum allowed is 80  max-len   152:1  error    This line has a length of 84. Maximum allowed is 80  max-len   153:1  error    This line has a length of 95. Maximum allowed is 80  max-len   167:1  error    This line has a length of 89. Maximum allowed is 80  max-len   168:1  error    This line has a length of 98. Maximum allowed is 80  max-len   170:1  error    This line has a length of 83. Maximum allowed is 80  max-len   213:1  error    Trailing spaces not allowed                          no-trailing-spaces   213:5  error    Newline required at end of file but not found        eol-last
✖ 11 problems (10 errors, 1 warning)
  2 errors and 0 warnings potentially fixable with the `--fix` option.

Error: functions predeploy error: Command terminated with non-zero exit code 1